/*
 * Copyright 2018 Gil Barbosa Reis <gilzoide@gmail.com>
 * This file is part of pega-texto-debugger.
 *
 * Pega-texto-debugger is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Pega-texto-debugger is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this pega-texto-debugger.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __PEGA_TEXTO_DEBUGGER_H__
#define __PEGA_TEXTO_DEBUGGER_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "pega-texto-debugger/ptdb.h"

/// Pega-texto-debugger version string, generated by the CMake build.
#define PTDB_VERSION "@PROJECT_VERSION@"

#ifdef __cplusplus
}
#endif

#endif

